# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae49385c2157f8fa6eec3d05ee8226e99b83e55765297fa44ee866ea997df86a2a4954b9e692672a79945de12fb9ee497bc91bc40fd18883710a01dd59f63530

test:
  secret_key_base: 9f09d3312b47bfd73cef1f22ac230fed60abf1d590214074d2fa014f18dc4a9ac99d1aa431aa091ac8d9f27076d7b44a803218aaea7bdede5d71cc95c1ea583d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
